apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-config
  namespace: banking-app
data:
  DB_HOST: "production-mysql-db.c6tk8iqi07be.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "production_db"
  REACT_APP_API_URL: https://bankapi.service:8080
